- name: bug
  color: "B60205"
  description: "Something isn't working"

- name: documentation
  color: "1D76DB"
  description: "Improvements or additions to documentation"

- name: enhancement
  color: "006B75"
  description: "New feature or request"

- name: refactor
  color: "0E8A16"
  description: "Something must be refactored."

- name: research
  color: "FBCA04"
  description: "Something must be explored further to gain a better understanding"

- name: major
  color: "FF0000"
  description: "Major version release (vx.0.0)"

- name: minor
  color: "FFA500"
  description: "Minor version release (v1.x.0)"

- name: patch
  color: "00FF00"
  description: "Patch version release (v1.0.x)"
