- name: epic
  color: "8E44AD"
  description: "A large task"

- name: bug
  color: "B60205"
  description: "Something isn't working"

- name: enhancement
  color: "006B75"
  description: "New feature or request"

- name: documentation
  color: "ADD8E6"
  description: "Documentation task"

- name: chore
  color: "FBCA04"
  description: "General task"
