name: 🐛 Bug
description: File a bug report here
labels: ["bug"]
assignees: devantler
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the bug.

  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: Describe the current behavior of the system.
      value: |
        - Behavior 1
        - Behavior 2
        - Behavior 3

  - type: textarea
    id: proposed
    attributes:
      label: Proposed behavior
      description: Describe the proposed behavior of the system.
      value: |
        - Behavior 1
        - Behavior 2
        - Behavior 3

  - type: textarea
    id: fixes
    attributes:
      label: Fixes
      description: List any issues that this bug fixes.
      value: |
        - Fixes #1
        - Fixes #2
        - Fixes #3
