name: 🧹 Chore
description: A general task that does not fit into other categories.
title: "[chore]: "
type: Chore
projects:
  - devantler-tech/5
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the chore.
