name: 🧹 Chore
description: A general task that does not fit into any other category
labels: ["chore"]
assignees: devantler
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the chore.
  
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: Provide a list of issues that this particular chore depends on.
      placeholder: |
        - #issue-number1
        - #issue-number2

  - type: textarea
    id: expected-work-done
    attributes:
      label: Expected work done
      description: Provide a list of expected changes to implement the chore.
      placeholder: |
        - Added...
        - Updated...
        - Deleted...

  - type: textarea
    id: postconditions
    attributes:
      label: Postconditions
      description: Describe the now satisfied conditions and provide a list of issues that depend on this particular chore.
      placeholder: |
        After implementing this chore, the following should be true:
        
        - Condition-1
        - Condition-1

        Given this new state, the following issues can now be implemented:

        - #issue-number-1
        - #issue-number-2
