name: 🧹 Chore
description: A general task that does not fit into any other category
projects:
  - devantler/4
#type: Task
assignees: devantler
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the chore.
