name: 📚 Documentation
description: Written text or illustration about a software system, or text embedded in the source code.
title: "[doc]: "
type: Documentation
projects:
  - devantler-tech/5
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the documentation.
