name: 🚀 Enhancement
description: Request a new feature
labels: ["enhancement"]
assignees: devantler
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this enhancement hasn't already been submitted by someone else by looking through other open/closed issues.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the enhancement.
  
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: Provide a list of issues that this particular enhancement depends on.
      placeholder: |
        - #issue-number1
        - #issue-number2

  - type: textarea
    id: expected-work-done
    attributes:
      label: Expected work done
      description: Provide a list of expected changes to implement the enhancement.
      placeholder: |
        - Added...
        - Updated...
        - Deleted...

  - type: textarea
    id: postconditions
    attributes:
      label: Postconditions
      description: Describe the now satisfied conditions and provide a list of issues that depend on this particular enhancement.
      placeholder: |
        After implementing this enhancement, the following should be true:
        
        - Condition-1
        - Condition-1

        Given this new state, the following issues can now be implemented:

        - #issue-number-1
        - #issue-number-2
