name: 🎯 Epic
description: A large task or endeavor providing value
title: "[epic]: "
type: Epic
projects:
  - devantler-tech/5
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the epic issue.
