name: 🚀 Enhancement
description: Request a new feature
labels: ["enhancement"]
assignees: devantler
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this enhancement hasn't already been submitted by someone else by looking through other open/closed issues.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the enhancement.
  
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: Provide a list of issues that this particular enhancement depends on.
      placeholder: |
        - #issue-number1
        - #issue-number2

  - type: textarea
    id: expected-work-done
    attributes:
      label: Expected work done
      description: Provide a list of expected changes to implement the enhancement.
      placeholder: |
        - #issue-number1
        - #issue-number2

  - type: textarea
    id: postconditions
    attributes:
      label: Postconditions
      description: Provide a list of issues that depend on this particular enhancement.
      placeholder: |
        - #issue-number1
        - #issue-number2
