name: Global Workflows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  replicate_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          patterns_to_include: '.github/workflows'
          patterns_to_ignore: '.github/workflows/global-workflows.yaml'
