name: Global Workflows

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  replicate_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          patterns_to_include: ".github/workflows"
          patterns_to_ignore: ".github/workflows/global-workflows.yaml"
          patterns_to_remove: ""
  replicate_pull_request_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          patterns_to_include: ".github/PULL_REQUEST_TEMPLATE.md"
          patterns_to_ignore: ""
          patterns_to_remove: ""
  replicate_renovate_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          patterns_to_include: ".github/renovate.json"
          patterns_to_ignore: ""
          patterns_to_remove: ""
  replicate_release_drafter_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          patterns_to_include: ".github/release-drafter.yml"
          patterns_to_ignore: ""
          patterns_to_remove: ""
  replicate_codeowners_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          patterns_to_include: ".github/CODEOWNERS"
          patterns_to_ignore: ""
          patterns_to_remove: ""
