name: Readme Tree

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  readme-tree:
    uses: devantler-tech/.github/.github/workflows/readme-tree.yaml@main
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
