name: Sync labels
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 1'

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: 'https://raw.githubusercontent.com/devantler/.github/main/.github/labels.yaml'
